name: code-reason2
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - compilers
  - pip:
      - transformers==4.57.3
      - datasets==4.4.1
      - evaluate==0.4.6
      - codebleu==0.7.0
      - rope==1.14.0