name: code-reason
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.2.25=hd43f75c_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libffi=3.4.4=h419075a_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h998d150_0
  - ncurses=6.4=h419075a_0
  - openssl=3.0.16=h998d150_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=h4bb2201_1
  - readline=8.2=h998d150_0
  - setuptools=78.1.1=py310hd43f75c_0
  - sqlite=3.45.3=h998d150_0
  - tk=8.6.14=h987d8db_0
  - wheel=0.45.1=py310hd43f75c_0
  - xz=5.6.4=h998d150_1
  - zlib=1.2.13=h998d150_1
  - pip:
        - accelerate==1.6.0
        - aiohappyeyeballs==2.6.1
        - aiohttp==3.11.18
        - aiosignal==1.3.2
        - annotated-types==0.7.0
        - anyio==4.9.0
        - astor==0.8.1
        - async-timeout==5.0.1
        - attrs==25.3.0
        - blake3==1.0.7
        - cachetools==6.2.0
        - cbor2==5.7.0
        - certifi==2025.4.26
        - cffi==2.0.0
        - charset-normalizer==3.4.2
        - click==8.2.1
        - cloudpickle==3.1.1
        - code-ast==0.1.1
        - codebleu
        - compressed-tensors==0.11.0
        - coverage==7.8.0
        - cupy-cuda12x==13.6.0
        - datasets==4.4.1
        - depyf==0.19.0
        - dill==0.3.8
        - diskcache==5.6.3
        - distro==1.9.0
        - dnspython==2.8.0
        - docker==7.1.0
        - einops==0.8.1
        - email-validator==2.3.0
        - evaluate==0.4.6
        - exceptiongroup==1.2.2
        - fastapi==0.118.2
        - fastapi-cli==0.0.13
        - fastapi-cloud-cli==0.3.1
        - fastrlock==0.8.3
        - filelock==3.20.0
        - frozendict==2.4.6
        - frozenlist==1.6.0
        - fsspec==2024.6.1
        - gguf==0.17.1
        - gitdb==4.0.12
        - gitpython==3.1.44
        - h11==0.16.0
        - hf-xet==1.1.10
        - httpcore==1.0.9
        - httptools==0.7.1
        - httpx==0.28.1
        - huggingface-hub==0.35.3
        - idna==3.10
        - iniconfig==2.1.0
        - interegular==0.3.3
        - jinja2==3.1.6
        - jiter==0.10.0
        - jsonschema==4.25.1
        - jsonschema-specifications==2025.9.1
        - lark==1.2.2
        - llguidance==0.7.30
        - llvmlite==0.44.0
        - lm-format-enforcer==0.11.3
        - markdown-it-py==4.0.0
        - markupsafe==2.1.5
        - mdurl==0.1.2
        - mistral-common==1.8.5
        - mpmath==1.3.0
        - msgpack==1.1.2
        - msgspec==0.19.0
        - multidict==6.4.3
        - multiprocess==0.70.16
        - networkx==3.3
        - ninja==1.13.0
        - numba==0.61.2
        - numpy==2.1.2
        - openai==2.3.0
        - openai-harmony==0.0.4
        - opencv-python-headless==4.12.0.88
        - outlines-core==0.2.11
        - packaging==25.0
        - pandas==2.2.3
        - partial-json-parser==0.2.1.1.post6
        - pillow==11.0.0
        - platformdirs==4.3.8
        - pluggy==1.5.0
        - prometheus-client==0.23.1
        - prometheus-fastapi-instrumentator==7.1.0
        - propcache==0.3.1
        - protobuf==6.31.1
        - psutil==7.0.0
        - py-cpuinfo==9.0.0
        - pyarrow==20.0.0
        - pybase64==1.4.2
        - pycountry==24.6.1
        - pycparser==2.23
        - pydantic==2.12.0
        - pydantic-core==2.41.1
        - pydantic-extra-types==2.10.6
        - pygments==2.19.2
        - pytest==8.3.5
        - python-dateutil==2.9.0.post0
        - python-dotenv==1.1.1
        - python-json-logger==4.0.0
        - python-multipart==0.0.20
        - pytoolconfig==1.3.1
        - pytz==2025.2
        - pyyaml==6.0.2
        - pyzmq==27.1.0
        - ray==2.49.2
        - referencing==0.36.2
        - regex==2024.11.6
        - requests==2.32.3
        - rich==14.2.0
        - rich-toolkit==0.15.1
        - rignore==0.7.0
        - rope==1.14.0
        - rpds-py==0.27.1
        - safetensors==0.5.3
        - scipy==1.15.3
        - sentencepiece==0.2.1
        - sentry-sdk==2.34.1
        - setproctitle==1.3.7
        - shellingham==1.5.4
        - six==1.17.0
        - smmap==5.0.2
        - sniffio==1.3.1
        - soundfile==0.13.1
        - soxr==1.0.0
        - starlette==0.48.0
        - sympy==1.14.0
        - tiktoken==0.12.0
        - tokenizers==0.22.1
        - tomli==2.2.1
        - torch==2.8.0
        - torchaudio==2.8.0
        - torchvision==0.23.0
        - tqdm==4.67.1
        - transformers==4.57.3
        - tree-sitter==0.21.3
        - tree-sitter-language-pack==0.13.0
        - tree-sitter-languages==1.10.2
        - tree-sitter-python
        - typer==0.19.2
        - typing-extensions==4.15.0
        - typing-inspection==0.4.2
        - tzdata==2025.2
        - urllib3==2.4.0
        - uvicorn==0.37.0
        - uvloop==0.21.0
        - vllm==0.11.0
        - wandb==0.21.1
        - watchfiles==1.1.0
        - websockets==15.0.1
        - xgrammar==0.1.25
        - xxhash==3.5.0
        - yarl==1.20.0
prefix: /users/rmachace/miniconda3/envs/code-reason
